### ISSUE TITLE
Application to surface evolution MC simulations

### ISSUE THREAD

**Issue by BeastyBlacksmith** [crstnbr/MonteCarlo.jl#1]
Hello Carsten,
I am about to start writing MC simulations to find the shape of a surface that minimizes a given energy ( such as bending energy or free energy of contained liquid ).
I wonder how much this fits into the scope of this package and what exactly has to be done to make this work.
As far as I see, I would need to implement at least a non-static lattice and setup a corresponding model type. Would that be all?

**Comment by carstenbauer** [comment]
With a one year delay, this doesn't really fall into the scope of the package. Generic (statistical) Monte Carlo tools might be able to help you.
