### ISSUE TITLE
Change effective Greens function

### ISSUE THREAD

**Issue by ffreyer** [crstnbr/MonteCarlo.jl#30]
We use the symmetric Trotter approximation to factorize propagators `B ~ exp(T + V) = exp(T/2) exp(V) exp(T/2)`. An update in DQMC changes `exp(V) -> exp(V') = (I + delta) exp(V)`. In order to write the determinant ratio in terms of the Greens function, we need to be able to isolate `(1 + delta)`, i.e we need to have `(I+delta) B` or `B (I + delta)`. For this, we introduce an effective Greens function with `B ~ exp(T/2) exp(T/2) exp(V)`, which can be mapped back to the normal Greens function by applying `G_normal = exp(-T/2) G exp(T/2)`. This allows us to pull `(I + delta)` to the right if both `exp(V)` and `(I + delta)` are diagonal. Otherwise we cannot permute them and we're stuck with `exp(T/2) exp(T/2) (I + delta) exp(V)`.

If we were to change the effective Greens function to use `B = exp(V) exp(T/2) exp(T/2)` this wouldn't be a problem. The normal Greens function would now be `G_normal = exp(T/2) G exp(-T/2)` and MC updates would need to use `G = G - G (I + delta (I - G))^-1 delta (I-G))` instead of `G = G - (I -G) (I + delta (I - G))^-1 delta G)`.

**Comment by carstenbauer** [comment]
I'm not sure I understand your matter here.

> In order to write the determinant ratio in terms of the Greens function, we need to be able to isolate (1 + delta), i.e we need to have (I+delta) B or B (I + delta). For this, we introduce an effective Greens function with `B ~ exp(T/2) exp(T/2) exp(V)`

The effective Green's function is only introduced for faster linear algebra - we save a sparse matrix multiplication for every application of `B`. Choosing VTT or TTV form shouldn't really matter for anything.

> This allows us to pull `(I + delta)` to the right if both `exp(V)` and `(I + delta)` are diagonal. Otherwise we cannot permute them and we're stuck with `exp(T/2) exp(T/2) (I + delta) exp(V)`.

In the SDW model, `exp(V)` isn't diagonal.

**Comment by ffreyer** [comment]
Let me try to rephrase my point.

At one point in the derivation of DQMC one rewrites the propagator `B = exp(-\Delta\tau H) = exp(-\Delta\tau (T+V)) = exp(-\Delta\tau T / 2) exp(-\Delta\tau V) exp(-\Delta\tau T /2) + O(\Delta\tau^3)` via the symmetric Trotter decomposition. The error can be checked by expanding the exponentials as sums and looking for the first power of `\Delta\tau` that differs, which is `\Delta\tau^3` in this case.

A DQMC update affects the Hubbard Stratonovich field which is only included in `V`. We write `exp(\Delta\tau V') = [I + delta] exp(\Delta\tau V)`. In order to write the updated Greens function in terms of the previous Greens function, we need to be able to write the updated propagator in terms of the old propagator, i.e. `B' = [I + delta] B` or `B' = B [I + delta]`. There are a couple of ways to get there.

#### 1) Use a lower order Trotter approximation

We could also use `exp(-\Delta\tau (T + V)) = exp(-\Delta\tau T) exp(-\Delta\tau V) + O(\Delta\tau^2) = exp(-\Delta\tau V) exp(-\Delta\tau T) + O(\Delta\tau^2)`. The error is now larger, but it is we get `B' = [I + delta] B` trivially.

#### 2) Define effective Greens function and ...

This is what I had in mind when I opened the issue. We define an effective Greens function `G_eff = exp(-\Delta\tau T/2) G exp(\Delta\tau T/2)` which can easily be mapped back to the normal Greens function. This leads to effective propagators `B = exp(-\Delta\tau T/2) exp(-\Delta\tau T/2) exp(-\Delta\tau V)`. We can then proceed in two ways:

###### 2.1) ... exchange terms via transpose
If `[I + delta]` and `exp(-\Delta\tau V)` are ~diagonal~ symmetric, they do not change when transposed, so `[I + delta]exp(-\Delta\tau V) = exp(-\Delta\tau V) [I + delta]`. With this we remain at an `O(\Delta\tau^3)` error.

###### 2.2) ... change the definition of delta
We can instead define the update via `exp(-\Delta\tau V') = exp(-\Delta\tau V) [I + delta]`. This way we trivially get the form `B' = B [I + delta]`, but `delta` maybe different. The error remains at `O(\Delta\tau^3)`

#### 3) Permute the terms in the Trotter decomposition
Instead of trapping `exp(-\Delta\tau V)` in the middle, we write `exp(-\Delta\tau T/2) exp(-\Delta\tau T/2) exp(-\Delta\tau V)` when doing the Trotter approximation. This however gives an error `O(\Delta\tau^2)`, so we might as well use solution 1). (I checked this by expanding each exponential up to (and including)third order in `\Delta\tau` and comparing to `exp(-\Delta\tau (T + V))` expanded up to (and including) third order. `\Delta\tau^2` terms are the first that differ)

---

So this isn't really an issue, but it is something that needs to be documented. With the definitions we have, what I call `delta` (`gamma` in the Hubbard model implementation) should generally be constructed via `exp(-\Delta\tau V') = exp(-\Delta\tau V) [I + \delta]`.
