### ISSUE TITLE
udt -> udt!

### ISSUE THREAD

**Issue by ffreyer** [crstnbr/MonteCarlo.jl#35]
Can we use `udt!` instead of `udt` here?
https://github.com/crstnbr/MonteCarlo.jl/blob/310391725eb0607d8d40c4cc4e10217a0d19a5a2/src/flavors/DQMC/stack.jl#L242

**Comment by ffreyer** [comment]
Also, somewhat unrelated, the line before should probably use `rmul!(mc.s.curr_U, Diagonal(mc.s.d))` and the line after `mul!(mc.s.t_stack[:, :, idx + 1],  T, mc.s.t_stack[:, :, idx])`

**Comment by carstenbauer** [comment]
It should, see https://github.com/crstnbr/dqmc/blob/master/src/stack.jl#L278

**Comment by ffreyer** [comment]
We can also use `mc.s.tmp` here, instead of `T`

**Comment by carstenbauer** [comment]
> We can also use `mc.s.tmp` here, instead of `T`

Shouldn't make (much of) a difference though, right? It is not going to be in-place in either case.
