### ISSUE TITLE
calculate_greens_and_logdet() fails for safe_mult > 1

### ISSUE THREAD

**Issue by ffreyer** [crstnbr/MonteCarlo.jl#36]
This is because the udt products are not finalized in `calculate_slice_matrix_chain` and `calculate_slice_matrix_chain_dagger`. To fix this, repeat

```julia
 U *= spdiagm(0 => D)
 U, D, Tnew = decompose_udt(U)
 T =  Tnew * T
 svs[:,svc] = log.(D)
 svc += 1
```
after the loop.

**Comment by carstenbauer** [comment]
Also here, it is useful to take a look at the changes I did in the private DQMC code.

See https://github.com/crstnbr/dqmc/blob/master/src/fermion_measurements.jl#L964, in particular the comment `# always decompose in the end`
