### ISSUE TITLE
CPU Utilization scaling with lattice size for DQMC. 

### ISSUE THREAD

**Issue by MasonProtter** [crstnbr/MonteCarlo.jl#48]
In the process of getting a feel for using the package, I tried running the following script:
```julia
using MonteCarlo, Distributions, DataFrames

Tdist = Normal(MonteCarlo.IsingTc, .64)
n_Ts = 2^5 # 2^8
Ts = sort!(rand(Tdist, n_Ts))
Ts = Ts[Ts.>=1.2]
Ts = Ts[Ts.<=3.8]
therm = 5*10^1  # 10^4
sweeps = 5*10^1 # 10^3

df = DataFrame(L=Int[], T=Float64[], BE=Float64[])

for L in 2 .^ [3, 4, 5] 
    println("L = ", L)
    for (i, T) in enumerate(Ts)
    	println("\t T = ", T)
	beta = 1/T

        model = HubbardModelAttractive(dims=2, L=L)
        dqmc = DQMC(model, beta=beta, delta_tau = (beta/100), slices=100, checkerboard=true)
        run!(dqmc, sweeps=sweeps, thermalization=therm, verbose=false)

	meas = MonteCarlo.measurements(dqmc)[:ME]
	push!(df, [L, T, mean(meas[:BosonEnergy].obs)])    
    end
end
```
and found that for `L = 2^3` and `L = 2^4`, I was getting 98% CPU utilization almost constantly across 8 threads, but for `L = 2^5`, CPU utilization dropped down to about 10% per thread, very occasionally spiking up to 50%. 

This is not a very advanced analysis and I'll soon try and dig into what's going on to see if this is an actual problem or just that for large lattices, its unavoidable for the CPUs to need to do more waiting, but in the meantime here's an issue to track in case anyone knows what may be going on.

**Comment by ffreyer** [comment]
Are you sure it's 10% per thread?

If it was 10% of all 8 threads it would make more sense to me. There is nothing explicitly multi-threaded in MonteCarlo, but BLAS has some inbuilt multithreading. All the mul! calls that happen downstream from `propagate()` (as well as calls to QR made from udt decomposition) should trace back to BLAS calls. The Monte Carlo update, i.e. `accept_local()` might not use BLAS, or maybe it can't use multithreading well.
Perhaps these differences are only picked up when they happen more slowly, i.e. for large systems.

**Comment by MasonProtter** [comment]
The system is reporting 10% per thread, but nearly 100% on the main thread (I didn't notice this part before because of the way `htop` reports utilization), so I guess that just means that the cost of the BLAS calls is scaling slower than than the cost of the single-threaded part.
