### ISSUE TITLE
Specify particle density instead of chemical potential

### ISSUE THREAD

**Issue by MasonProtter** [crstnbr/MonteCarlo.jl#52]
We should allow users to specify a particle density instead of chemical potential in DQMC.

**Comment by carstenbauer** [comment]
Generally, that's basically impossible. I mean for known systems (the Hubbard model) we could try to use established knowledge about their relation. But generally, this would require a self consistent determination of the correct mu, involving multiple DQMC simulations itself.

(Papers that state that they fixed the density are just sweeping this fact under the carpet.)
